swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger Rest Article
consumes:
  - application/json
produces:
  - application/json

basePath: /api

# Paths supported by the server application
paths:
  /avocado:
    get:
      operationId: avocado.read_all
      tags:
        - Avocado
      summary: Read the entire set of avocado
      description: Read the entire set of avocado
      responses:
        200:
          description: Successfully read avocado set operation
          schema:
            type: array
            items:
              properties:
                date:
                  type: string
                  description: date of the avocado
                avgprice:
                  type: number
                  format: double
                  description: avgprice of the person
                totalvol:
                  type: integer
                  description: totalvol of the person
                avo_a:
                  type: integer
                  description: avo_a of the person
                avo_b:
                  type: number
                  format: double
                  description: avo_b of the person
                avo_c:
                  type: number
                  format: double
                  description: avo_c of the person
                type:
                  type: object
                  properties:
                    typeid:
                      type: integer
                      description: typeid of associated avocado
                    type:
                      type: string
                      description: type of associated avocado
                regionid:
                  type: object
                  properties:
                    regionid:
                      type: integer
                      description: regionid of associated avocado
                    region:
                      type: string
                      description: region of associated avocado